### ISSUE TITLE
Add option to return intermediate detector data structures from `load_nexus` 

### ISSUE THREAD

**Issue by Tom-Willemsen** [scipp/scippneutron#138]
It may be useful for some operations to load "intermediate" detector data structures such as the event index from `load_nexus`. Probably make the binning/mapping to pixel step optional.

**Comment by SimonHeybrock** [comment]
Basically, this should return data as stored on disk in the `NXevent_data` groups. Note that these are already loaded, but there is no option to return this.

**Comment by OwenArnold** [comment]
Would be nice if this work (or subsequent) could demo how these options could be used. It might be relevant for event filtering for example.
