### ISSUE TITLE
Custom components in instrument view, part 2

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scippneutron#154]
This is a list of things I think we may need to change/add in the custom component support:

- Current mechanism relies on meta data with given name that contains the position. This generally not the case, e.g., a chopper or monitor is typically a scalar variable with `dtype=DataArray`. The position would be an attribute of this nested array.
- Automatic component size and text size setup is bound to cause trouble.
- User may want display name different from coord name, e.g., to display "sample" instead of "sample_position".

Suggestion:
- `components` should still be a `dict`, I think this is good.
- Keys of `components` should be *display names*
- Values should be dicts, defining position, shape, color, ...

Example:
```python
scn.instrument_view(
    da,
    components={
        'source': {
            'position': 'source_position',
            'color': 'ababab',
            'size': 0.1 * sc.Unit('m'),
            'text_size': 1.0 * sc.Unit('m'),
            'type': 'cube'
        },
        'monitor3': {
            'position': da.attrs['monitor3'].value.coords['position'],
            'color': 'fafafa',
            'type': 'cube'
        },
    })
```

@OwenArnold @nvaytet

**Comment by OwenArnold** [comment]
Seems reasonable to me though I'm not sure if any of this (for example color) should gain a sensible default if not specified.
