### ISSUE TITLE
Conversion from mantid truncates events to int

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scippneutron#201]
Loading event data written by MCStas via `scan.load` turns float events into ints. The reason is that mantid marks the data as being non weighted events. But loading the same file in MantidFramework and saving to nexus produces a file that can be loaded correctly by scippneutron.

**Comment by SimonHeybrock** [comment]
Are you referring to this: https://github.com/scipp/scippneutron/blob/94f877830e5c8c50a5559ea2089674a6ac3de8dc/python/src/scippneutron/mantid.py#L617-L619?

Is our check wrong, or is the Mantid flag broken?

**Comment by jl-wynen** [comment]
> Are you referring to this: 

Yes

> Is our check wrong, or is the Mantid flag broken?

Don't know, the Mantid docs do not describe it. It looks like Mantid is able to handle the data because it writes a valid NeXus file. So either we interpret the flag wrong or Mantid determines how to handle the data independently from the flag.

**Comment by SimonHeybrock** [comment]
In the Mantid implementation a different event type actually means that data is stored in a different vector (because different event type implies a different struct (without or without weight fields)). So it is really odd that it can save it correctly but reports the wrong type.

**Comment by jl-wynen** [comment]
Can we detect which vector it stores the data in and use that instead of the enum?

**Comment by SimonHeybrock** [comment]
I doubt it, since that is hidden in the C++ implementation of `EventList`.
