### ISSUE TITLE
Capture Mantid logging output and redirect to scipp logger

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scippneutron#220]
2 options:
- Capture stdout when calling mantid algorithms and send output to logger.
  - Would require parsing log messages.
  - There could be issues with multi threaded code (redirecting stream need to be done correctly across threads)
- Add log handler in Mantid (C++).

**Comment by SimonHeybrock** [comment]
Should we close this, or keep it open until you have also implemented the setup/config?

**Comment by jl-wynen** [comment]
Can be closed now because the task has been done now. The config is a separate issue.
