### ISSUE TITLE
Names of file loaders

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scippneutron#221]
- Should `scn.load` be renamed to be explicit about using mantid?
- Inconsistent keyword args

**Comment by SimonHeybrock** [comment]
> Should scn.load be renamed to be explicit about using mantid?

We should do that soon, and add a deprecation warning to the old one.

**Comment by jl-wynen** [comment]
Let's finally do this and rename `load` to `load_mantid` and deprecate `load` for 6 months!

Unfortunately, I don't remember what I mean by 
> Inconsistent keyword args

**Comment by SimonHeybrock** [comment]
`load_mantid` may be slightly misleading, since it is not (just) for loading Mantid files?

**Comment by jl-wynen** [comment]
`load_with_mantid`, `load_via_mantid`, `mantid_load`?

**Comment by jl-wynen** [comment]
Or move it into the mantid module and don't import at top level. So users can use `scn.mantid.load`.

**Comment by SimonHeybrock** [comment]
Submodule sounds good 👍

**Comment by SimonHeybrock** [comment]
On the other hand... we may want to add scippnexus-based loaders, and we will not name them `scn.scippnexus.load_abc`? So maybe `load_with_mantid` is best?
