### ISSUE TITLE
Include beamline components in instrument view

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scippneutron#23]
How can we display other beamline components in the instrument view, not just pixels?
- monitors
- source
- sample

**Comment by matthew-d-jones** [comment]
In the [NeXus Constructor](https://github.com/ess-dmsc/nexus-constructor) tool we use low-opacity cubes to indicate the position of any components which don't have an explicitly defined shape. A problem with this approach is determining how large these "placeholder" shapes should be.
