### ISSUE TITLE
Transform applied to offset in NXtransformations loading?

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scippneutron#273]
Consider:
https://github.com/scipp/scippneutron/blob/2e39bea24387729c84c3a370e9d85771ad9879b1/src/scippneutron/file_loading/_transformations.py#L217

https://manual.nexusformat.org/classes/base_classes/NXtransformations.html says:

>  `o` is given by the offset attribute, `t` is given by the `vector` attribute multiplied by the field value

For me this should therefore give a translation defined as `value * vector + offset`, i.e., apart from the sign, the parenthesis are wrong.

Related: #272, which affects the sign in the equation.

**Comment by nvaytet** [comment]
I think I understand like you that the vector is a unit vector, multiplied by a value to give it a magnitude, and then you add an offset so that you know which point to start from.
So the parentheses do appear to be wrong.
