### ISSUE TITLE
load_nexus does not work with event monitors that have data in separate group

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scippneutron#287]
`load_nexus` is broken for event mode monitors if the event data is stored in a separate `NXevent_data` group.
Given a file with structure (brackets indicate NXclass)
```
- monitor_1 [NXmonitor]
  - monitor_1_events [NXevent_data]
- larmor_detector [NXdetector]
  - larmor_detector_events [NXevent_data]
```
`load_nexus` finds 2 event data groups, loads them, and concatenates them all into the data for `larmod_detector` and in the process discards the pixel positions.

There is a hacky fix based on checking the NXclass of parent groups on branch [larmor-nexus-patch](https://github.com/scipp/scippneutron/tree/larmor-nexus-patch). But this will not work if the event data is stored nested in other groups. E.g. monitor events that are stored at the top level and not nested in an `NXmonitor`.

We need a proper way to only look at groups related to NXdetector. But since the event data can be in arbitrary places in the file, that seems very difficult to do.

**Comment by SimonHeybrock** [comment]
Another indicator that the "automatic" way of loading files into a specific schema is too limited and error-prone?

> We need a proper way to only look at groups related to NXdetector. But since the event data can be in arbitrary places in the file, that seems very difficult to do.

I feel what we need to do is ignore any `NXevent_data` that is not referenced by an `NXdetector`. The matching based on HDF5 group names is too error prone? But this will likely break loading of a number of files from other facilities?

**Comment by SimonHeybrock** [comment]
My suggestion would be to simply not consider NXevent_data for loading. Instead, simply load all NXdetector groups. This would imply that files that have a purely name-based association between NXdetector and NXevent_data cannot be loaded.

Are we aware of any files that actually do this?

**Comment by SimonHeybrock** [comment]
> Are we aware of any files that actually do this?

Files from ISIS (checked only WISH) appear to do this :(

**Comment by SimonHeybrock** [comment]
As far as I can tell the current version of `load_nexus` is not doing name-based association anymore anyway. That is, after scipp/scippnexus#21 this problem may have disappeared.
