### ISSUE TITLE
Implement frame unwrapping (and pulse skipping) into an actual utility

### ISSUE THREAD

**Issue by nvaytet** [scipp/scippneutron#402]
Details on the algorithm to implement can be found [here](https://scipp.github.io/scippneutron/reference/frame-unwrapping.html).

- Ask the IDSs if they need tools to create time-distance diagrams for debugging (e.g. check that the frames look ok when doing pulse-skipping).

- We may also need to check for drift, analysing many pulses over a long period of time.

- Previous issue and more details in #236

**Comment by SimonHeybrock** [comment]
Subtasks:

- [ ] Define required input parameter and check back with IDSs if those make sense.
- [ ] Implement transformation, see #236.
- [ ] With IDSs, figure out how those parameters should be obtained.
- [ ] Implement functionality to compute those parameters. This might involve, e.g., parsing and processing chopper parameters.

**Comment by SimonHeybrock** [comment]
This is mostly addressed by #472 and #468.
