### ISSUE TITLE
GSAS-II file writer

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scippneutron#413]
Need to find out which parts of the format are required. At the minimum, we need to save files that can be read by easyDiffraction.

**Comment by jl-wynen** [comment]
easyDiffraction does not actually support GSAS files, only CIF. It seems like only XYE files are required. Waiting for concrete requirements to be written down.

**Comment by SimonHeybrock** [comment]
We should strongly consider using `pandas` for the actual formatting/writing, if possible.

**Comment by jl-wynen** [comment]
`numpy.savetxt` is probably sufficient and it lets us avoid an extra dependency.
Also, XYE is so simple that it can be done manually in 3 lines of Python.

**Comment by SimonHeybrock** [comment]
Right, as long as we only have 1-D data, performance will not be relevant, so numpy should indeed by sufficient.
