### ISSUE TITLE
Compute time at sample

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scippneutron#489]
This is required for event data filtering for fast sample environment parameters, e.g., in ESSsans.

Should this be added to the regular coord transform graphs that ScippNeutron provides?

**Comment by jokasimr** [comment]
Is the time at the sample $t_s = L_1/v$?

**Comment by SimonHeybrock** [comment]
Almost, this is about the *absolute* time at the sample, so $t_0 + t_s$. It is probably easiest to calculate backwards from the detector position (i.e., we do not require $L_1$).

**Comment by jokasimr** [comment]
Okay I see, so we should compute the absolute time like $t_{abs,\ s} = t_0 + t_s = t_0 + t_d - L_2 / v$?

**Comment by SimonHeybrock** [comment]
> Okay I see, so we should compute the absolute time like tabs, s=t0+ts=t0+td−L2/v?

Yes, and we might go via wavelength, since $v$ is generally not required, but wavelength is computed in many cases already.

**Comment by jokasimr** [comment]
Where do we get $t_0$ (the time when the neutron passes the point where L=0)?
