### ISSUE TITLE
explore_data tutorial instrument_view with issue

### ISSUE THREAD

**Issue by jorobledo** [scipp/scippneutron#508]
Hi all,

Was trying out `scippneutron` and following up with the tutorial [1_exploring-data.html](https://scipp.github.io/scippneutron/tutorials/1_exploring-data.html) and encountered two small issues which I worked around. I installed scippneutron by `pip install scippneutron[all]`  in a new pyenv on Ubuntu.

- When wanting to visualize instrument with `scn.instrument_view()` missing `pythreejs` dependency (installed it manually afterwards).
- Then got an error on the plotting:
![image](https://github.com/scipp/scippneutron/assets/46170369/777d0a68-bcbc-4e05-82bc-05ce922a0706)
which was solved by modifying `scene = fig.children[0].canvas.scene` to `scene = fig.canvas.scene` in `instrument_view.py`. 

Then it worked smoothly., but might as well report it.
Nice job btw.!

**Comment by jl-wynen** [comment]
Concerning the first point, the `all` extra is a bit misleading. If you want interactive (3d) plots in Jupyter, you need the `interactive` extra: `pip install scippneutron[all, interactive]`. I'm going to change this in the docs.

**Comment by nvaytet** [comment]
> The second issue was actually fixed in #505. We should make a release...

I was waiting for #507 to make a release. @MridulS what's the status there?
