### ISSUE TITLE
Recalculate component positions when motion axis updates

### ISSUE THREAD

**Issue by matthew-d-jones** [scipp/scippneutron#76]
The full chain of transformations from the run start message should be cached and new pixel positions emitted with the streamed data chunk when one of the transformation values changes (motion axis has new value).
This can occur when one or more of the transformations in the chain contains a `stream`.

It might make sense to tackle #34 first because it is closely related and probably easier to implement.

**Comment by SimonHeybrock** [comment]
For future reference, scipp/essreduce#96.
