### ISSUE TITLE
More unit conversions

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scippneutron#94]
- [x] Implement convert on top of `transform_coords`. 
- [x] Add basic building blocks, e.g. straight line flight paths, too to wavelength.
- [x] Provide helpers to construct custom graphs

Consider requirements from
- Reflectometry
- Single crystal
- Inelastic (crystal and powder)

Concrete building blocks should be constructed when needed and together with IDSs

**Comment by SimonHeybrock** [comment]
Depends on #117 and scipp/scipp#2058.

**Comment by jl-wynen** [comment]
Closing this as the basic tasks are done. New conversions will be implemented as they are needed.
